export const fields = {
  AddCustomerForm: [
    'accountName',
    'parentAccount',
    'accountNumber',
    'totalEmployees',
    'email',
    'website',
    'industry',
    'accountSite',
    'customerPriority',
    'noOfLocation',
    'description',
    'billingAddressLine1',
    'billingAddressLine2',
    'billingCity',
    'billingStateCode',
    'billingPostalCode',
    'billingTo',
    'billingAttn',
    'billingDirections',
    'shippingAddressLine1',
    'shippingAddressLine2',
    'shippingCity',
    'shippingStateCode',
    'shippingPostalCode',
  ],
  AddVendorForm: [
    'name',
    'email_address',
    'website',
    'supplierAddressLine1',
    'supplierAddressLine2',
    'supplierCity',
    'supplierStateCode',
    'supplierPostalCode',
    'supplierTo',
    'supplierAttn',
    'supplierDirections',
  ],
  AddProductForm: ['supplierProductId', 'title', 'description', 'shippingTimeInDays'],
  AddEmployeeForm: [
    'firstName',
    'middleName',
    'lastName',
    'designation',
    'department',
    'email_address',
    'linkedIn',
    'employeeAddressLine1',
    'employeeAddressLine2',
    'employeeCity',
    'employeeStateCode',
    'employeePostalCode',
  ],
};
